### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by njh** [ktheory/maildir#27]
I just checked out a local copy of the codebase and ran the tests but got some errors:

```
$ rbenv local 2.4.4
$ bundle install
Using rake 12.3.2
Using concurrent-ruby 1.1.5
Using i18n 1.5.1
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.3
Using bundler 2.0.1
Using fakefs 0.13.3
Using json 2.2.0
Using mini_mime 1.0.1
Using mail 2.7.1
Using maildir 2.2.1 from source at `.`
Using shoulda-context 1.2.2
Using shoulda-matchers 3.1.3
Using shoulda 3.6.0
Bundle complete! 6 Gemfile dependencies, 16 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
$ bundle exec rake test
/Users/humfrn01/.rbenv/versions/2.4.4/bin/ruby -w -I"lib" -I"/Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.2/lib" "/Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.2/lib/rake/rake_test_loader.rb" "test/test_maildir.rb" "test/test_message.rb" "test/test_serializers.rb" "test/test_unique_name.rb" 
/Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/shoulda-matchers-3.1.3/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:229: warning: method redefined; discarding old model
/Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/shoulda-matchers-3.1.3/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:149: warning: previous definition of model was here
/Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/shoulda-context-1.2.2/lib/shoulda/context/context.rb:400: warning: assigned but unused variable - context
  * DEFERRED: Message#utime should update the messages atime. 
Run options: --seed 12390

# Running:

........../Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/mail-2.7.1/lib/mail/parsers/content_type_parser.rb:939: warning: statement not reached
/Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/mail-2.7.1/lib/mail/parsers/content_type_parser.rb:963: warning: statement not reached
/Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/mail-2.7.1/lib/mail/parsers/content_type_parser.rb:709: warning: assigned but unused variable - testEof
....................E......................E.............

Fabulous run in 0.434162s, 154.3203 runs/s, 209.5992 assertions/s.

  1) Error:
TestMessage#test_: A processed message should add and remove flags. :
NoMethodError: undefined method `blank?' for "S":String
    /Users/humfrn01/Projects/ruby-maildir/lib/maildir/message.rb:143:in `remove_flag'
    /Users/humfrn01/Projects/ruby-maildir/test/test_message.rb:131:in `block (2 levels) in <class:TestMessage>'
    /Users/humfrn01/Projects/ruby-maildir/test/test_message.rb:136:in `instance_exec'
    /Users/humfrn01/Projects/ruby-maildir/test/test_message.rb:136:in `block in create_test_from_should_hash'

  2) Error:
TestMaildir#test_: multiple flags should be removed from flag list. :
NoMethodError: undefined method `blank?' for "XYZ":String
    /Users/humfrn01/Projects/ruby-maildir/lib/maildir/message.rb:143:in `remove_flag'
    /Users/humfrn01/Projects/ruby-maildir/test/test_maildir.rb:126:in `block (2 levels) in <class:TestMaildir>'
    /Users/humfrn01/Projects/ruby-maildir/test/test_maildir.rb:129:in `instance_exec'
    /Users/humfrn01/Projects/ruby-maildir/test/test_maildir.rb:129:in `block in create_test_from_should_hash'

67 runs, 91 assertions, 0 failures, 2 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -w -I"lib" -I"/Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.2/lib" "/Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.2/lib/rake/rake_test_loader.rb" "test/test_maildir.rb" "test/test_message.rb" "test/test_serializers.rb" "test/test_unique_name.rb" ]
/Users/humfrn01/.rbenv/versions/2.4.4/bin/bundle:23:in `load'
/Users/humfrn01/.rbenv/versions/2.4.4/bin/bundle:23:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

`activesupport` is getting pulled in but I am not sure why `blank?` is undefined - or why Tavis is passing....

**Comment by todd-a-jacobs** [comment]
Nothing is explicitly pulling in ActiveSupport core extensions. It is being implicitly pulled in by shoulda-matchers:

```
  specs:
    activesupport (5.2.3)
    shoulda-matchers (3.1.3)
      activesupport (>= 4.0.0)
```

It seems that there's been a breaking change since the last time someone looked at the code base, and that Travis is resolving to some earlier versions of dependencies since very few of them are locked. I can think of a couple of likely fixes off the top of my head:

1. Explicitly `require 'active_support/core_ext/object/blank.rb' in the gem. This seems easiest.
1. Update or replace shoulda (although this might require refactoring a lot of tests).
1. Use refinements to provide #blank? where it's needed.

There may be other solutions, too. These are just my off-the-cuff ideas based on cursory inspection.

**Comment by njh** [comment]
Thanks!

Gertting some warnings from the `shoulda` and `mail` gems but tests passing now.

```
~/Projects/ruby-maildir(master) $ bundle exec rake test
/Users/humfrn01/.rbenv/versions/2.4.4/bin/ruby -w -I"lib" -I"/Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.2/lib" "/Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.2/lib/rake/rake_test_loader.rb" "test/test_maildir.rb" "test/test_message.rb" "test/test_serializers.rb" "test/test_unique_name.rb" 
/Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/shoulda-matchers-3.1.3/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:229: warning: method redefined; discarding old model
/Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/shoulda-matchers-3.1.3/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:149: warning: previous definition of model was here
/Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/shoulda-context-1.2.2/lib/shoulda/context/context.rb:400: warning: assigned but unused variable - context
  * DEFERRED: Message#utime should update the messages atime. 
Run options: --seed 62353

# Running:

..../Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/mail-2.7.1/lib/mail/parsers/content_type_parser.rb:939: warning: statement not reached
/Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/mail-2.7.1/lib/mail/parsers/content_type_parser.rb:963: warning: statement not reached
/Users/humfrn01/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/mail-2.7.1/lib/mail/parsers/content_type_parser.rb:709: warning: assigned but unused variable - testEof
...............................................................

Fabulous run in 0.642011s, 104.3596 runs/s, 146.4149 assertions/s.

67 runs, 94 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by todd-a-jacobs** [comment]
@njh I suspect the warnings (not errors) are:

1. A result of using FakeFS instead of a real filesystem in the maildir test suites. I don't think FakeFS really supports atime, so that warning is probably to be expected.
1. The other warnings are Ruby parser warnings from Mikel Lindsaar's mail gem, which we don't maintain. They should probably be [reported upstream](https://github.com/mikel/mail/issues) if you'd like to see them go away.

I'm glad the errors were easy to fix, and that you brought them to my attention. Thank you! If you have any related-but-different issues, please feel free to open them as new issues.
